#
# Install python on a host - a pre-requisite for using ansible
#
---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Apt update
      raw: apt -y update
    - name: Install python
      raw: apt install -y python